version: '3'

services:
  postgresql:
    image: "bitnami/postgresql:latest"
    ports:
      - "5432:5432"
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

  schema-tenancy:
    build: .
    container_name: schema-tenancy
    environment:
      SERVER_PORT: 8000
      DB_HOST: postgresql
      DB_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      DB_DRIVER: org.postgresql.Driver
    ports:
      - "8000:8000"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root.root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8099:80"
    restart: unless-stopped
