server:
  port: ${SERVER_PORT:8000}

spring:
  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5432}
    name: ${POSTGRES_DB:postgres}
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.name}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}

  jpa:
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

multitenancy:
  schema-cache:
    maximumSize: 100
    expireAfterAccess: 10
  master:
    repository:
      packages: com.example.schematenancy.multitenancy.repositories
    entityManager:
      packages: com.example.schematenancy.multitenancy.models
  tenant:
    repository:
      packages: com.example.schematenancy.repository
    entityManager:
      packages: com.example.schematenancy.model
